in this file i will predict whether a person survived or not without using pipelines

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import minmax_scale
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv("../../datasets/train.csv")
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
409,410,0,3,"Lefebre, Miss. Ida",female,NaN,3,1,4133,25.4667,NaN,S
759,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5000,B77,S
554,555,1,3,"Ohman, Miss. Velin",female,22.0,0,0,347085,7.7750,NaN,S
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S
79,80,1,3,"Dowdell, Miss. Elizabeth",female,30.0,0,0,364516,12.4750,NaN,S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.drop(columns = ['PassengerId',  "Name", "Ticket" , "Cabin"] , inplace = True)
df.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [7]:
X_train , X_test , Y_train , Y_test = train_test_split(df.drop(columns = ["Survived"]), df["Survived"] , test_size= 0.3)

In [8]:
X_train.sample(3)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
296       3  male  23.5      0      0   7.2292        C
91        3  male  20.0      0      0   7.8542        S
50        3  male   7.0      4      1  39.6875        S

In [9]:
Y_train.sample(3)

281    0
421    0
116    0
Name: Survived, dtype: int64

In [10]:
si = SimpleImputer()
si_embarked = SimpleImputer(strategy= "most_frequent")